FROM tomcat:latest

COPY ./tomcat_conf/ /usr/local/tomcat/conf/

RUN rm -rf /usr/local/tomcat/webapps/*

COPY ./target/*.war /usr/local/tomcat/webapps/*.war

EXPOSE 80
EXPOSE 443

VOLUME /usr/local/tomcat/logs

CMD ["catalina.sh", "run"]